baseURL = "http://example.org/"
languageCode = "ja"
title = "SUEP"
theme="pulp"

[params]
    author = "SUEP"
    avatar = "networking.png"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        This site is for an app. called SUEP.
    """
    publicationYear = "2021"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "Post"
    #name = "App" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/post/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/SU_EventsPortal"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/htnabe"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:t_official@t-pot.me"
    weight = 40
